package mess

import (
	"github.com/emersion/go-imap/v2"
)

type UpdateType int

const (
	UpdNewMessage UpdateType = iota
	UpdFlags
	UpdRemoved
	UpdMboxDestroyed
)

type Update[MailboxKey comparable] struct {
	Type     UpdateType
	Key      MailboxKey
	SeqSet   imap.UIDSet `json:",omitempty"`
	NewFlags []imap.Flag `json:",omitempty"`
}

// ExternalUpdate deserializes externally received update and dispatches
// it internal.
func (m *Manager[MailboxKey]) ExternalUpdate(upd Update[MailboxKey]) {
	switch upd.Type {
	case UpdNewMessage:
		// We push back the responsibility of storing \Recent flag
		// to the Manager object that generated the update in the first
		// place (we assume it was generated using SetExternalSink).
		//
		// Such Manager will either assign \Recent to one of its local
		// connections or return storeRecent so backend object using this
		// Manager will save the flag.
		m.newMessages(upd.Key, upd.SeqSet)
	case UpdFlags:
		if len(upd.SeqSet) != 1 {
			return
		}
		uid := upd.SeqSet[0].Start

		m.flagsChanged(upd.Key, uid, upd.NewFlags)
	case UpdRemoved:
		m.removedSet(upd.Key, upd.SeqSet)
	case UpdMboxDestroyed:
		m.mailboxDestroyed(upd.Key)
	}
}

// SetExternalSink sets the channel where all updates
// generated by this Manager will be serialized.
//
// Calling this multiple times will replace previosuly set
// channel. Call with nil to disable serialization.
//
// It is not safe to call SetExternalSink concurrently
// with other operations.
func (m *Manager[MailboxKey]) SetExternalSink(upds chan<- Update[MailboxKey]) {
	m.sink = upds
}
